{
 "title": "Rocket.Chat Dashboard - Basic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "server", "label": "server", "query": "rocketchat_ddp_connected_users" }
  ]
 },
 "panels": [
  { "title": "Summary Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Release",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "rocketchat_version{job=\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Site",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "rocketchat_version{job=\"$server\"}",
     "legendFormat": "{{site_url}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rocketchat_instance_count{job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Users Diff",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "DM Channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rocketchat_direct_total{job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Private Groups",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rocketchat_private_groups_total{job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_online{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Away",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_away{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Livechats",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rocketchat_livechat_total{job=\"$server\"}"
    }
   ]
  },
  {
   "title": "DDP Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Messages  Diff",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{job=\"$server\"})"
    }
   ]
  },
  {
   "title": "Livechat messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rocketchat_livechat_messages_total{job=\"$server\"}"
    }
   ]
  },
  { "title": "Moving Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages Sent Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_messages_total{job=\"$server\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Messages Sent (5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent{job=\"$server\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Users Presence",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rocketchat_users_online{job=\"$server\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "avg(rocketchat_users_away{job=\"$server\"})",
     "legendFormat": "Away"
    }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{job=\"$server\"})",
     "legendFormat": "Connected Users"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count{job=\"$server\"})",
     "legendFormat": "All Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth{job=\"$server\"})",
     "legendFormat": "Authenticated Sessions "
    }
   ]
  },
  {
   "title": "Oplog",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rocketchat_oplog{job=\"$server\"}[5m])) by (collection,op)",
     "legendFormat": "{{collection}}/{{op}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "max(rocketchat_users_total)", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "max(rocketchat_rooms_total)", "legendFormat": "Rooms" }
   ]
  },
  {
   "title": "Notifications Total",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_notification_sent) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  },
  {
   "title": "Notifications / Minute",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_notification_sent[5m])) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Node Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "nodejs_version_info{job=\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests_total{job=\"$server\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"$server\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (space) (nodejs_heap_size_used_bytes{job=\"$server\"})",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"$server\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_version_info{job=\"$server\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method) * sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks) by (callback) * sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_hooks) by (hook) * sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api) by (entrypoint) * sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}